apiVersion: nmstate.io/v1
kind: NodeNetworkConfigurationPolicy
metadata:
  name: br-hcp-eno2-vlan12
spec:
  nodeSelector:
    kubernetes.io/hostname: shiftnode1
  desiredState:
    interfaces:
    - name: eno2.12
      type: vlan
      state: up
      vlan:
        base-iface: eno2
        id: 12
      ipv4:
        enabled: false
      ipv6:
        enabled: false
    - name: br-hcp
      type: linux-bridge
      state: up
      bridge:
        options:
          stp:
            enabled: false
        port:
        - name: eno2.12
      ipv4:
        enabled: true
        dhcp: false
        address:
        - ip: 172.16.3.17
          prefix-length: 24
      ipv6:
        enabled: false
    routes:
      config:
      - destination: 0.0.0.0/0
        next-hop-address: 172.16.3.1
        next-hop-interface: br-hcp
        table-id: 12
    route-rules:
      config:
      - ip-to: 172.30.0.0/16
        route-table: 254
        priority: 80
      - ip-to: 10.128.0.0/14
        route-table: 254
        priority: 81
      - ip-from: 172.16.3.0/24
        route-table: 12
        priority: 100
---
apiVersion: nmstate.io/v1
kind: NodeNetworkConfigurationPolicy
metadata:
  name: br-hcp-shiftnode2-vlan12
spec:
  nodeSelector:
    kubernetes.io/hostname: shiftnode2
  desiredState:
    interfaces:
    - name: hcp2v12
      type: vlan
      state: up
      ipv4:
        enabled: false
      ipv6:
        enabled: false
      vlan:
        base-iface: enp0s20f0u2u4
        id: 12
    - name: enp2s0.12
      type: vlan
      state: absent
    - name: br-hcp
      type: linux-bridge
      state: up
      ipv4:
        enabled: true
        dhcp: false
        address:
        - ip: 172.16.3.18
          prefix-length: 24
      ipv6:
        enabled: false
      bridge:
        options:
          stp:
            enabled: false
        port:
        - name: hcp2v12
    route-rules:
      config:
      - ip-to: 172.30.0.0/16
        route-table: 254
        priority: 80
      - ip-to: 10.128.0.0/14
        route-table: 254
        priority: 81
      - ip-from: 172.16.3.0/24
        priority: 100
        route-table: 12
    routes:
      config:
      - destination: 0.0.0.0/0
        next-hop-address: 172.16.3.1
        next-hop-interface: br-hcp
        table-id: 12
---
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: hcp-eno2-vlan12
  namespace: default
  annotations:
    k8s.v1.cni.cncf.io/resourceName: bridge.network.kubevirt.io/br-hcp
spec:
  config: |-
    {
      "cniVersion": "0.3.1",
      "name": "hcp-eno2-vlan12",
      "type": "cnv-bridge",
      "bridge": "br-hcp",
      "macspoofchk": true
    }
