apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: hcp-eno2-vlan12-pool
  namespace: metallb-system
spec:
  addresses:
  - 172.16.3.2-172.16.3.5
  autoAssign: true
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: hcp-eno2-vlan12-pool
  namespace: metallb-system
spec:
  ipAddressPools:
  - hcp-eno2-vlan12-pool
  interfaces:
  - br-hcp
  nodeSelectors:
  - matchExpressions:
    - key: kubernetes.io/hostname
      operator: In
      values:
      - shiftnode2
