apiVersion: v1
kind: Service
metadata:
  name: router-hcp-ignition-vlan12
  namespace: openshift-ingress
  annotations:
    metallb.io/address-pool: hcp-eno2-vlan12-pool
spec:
  type: LoadBalancer
  loadBalancerIP: 172.16.3.4
  allocateLoadBalancerNodePorts: false
  externalTrafficPolicy: Local
  selector:
    ingresscontroller.operator.openshift.io/deployment-ingresscontroller: default
  ports:
  - name: https
    protocol: TCP
    port: 443
    targetPort: 443
