apiVersion: hypershift.openshift.io/v1beta1
kind: NodePool
metadata:
  name: workers
  namespace: clusters-lab-hcp
spec:
  arch: amd64
  clusterName: lab-hcp
  management:
    autoRepair: false
    replace:
      rollingUpdate:
        maxSurge: 1
        maxUnavailable: 1
      strategy: RollingUpdate
    upgradeType: Replace
  nodeDrainTimeout: 0s
  nodeVolumeDetachTimeout: 0s
  platform:
    kubevirt:
      additionalNetworks:
      - name: default/hcp-eno2-vlan12
      attachDefaultNetwork: false
      compute:
        cores: 4
        memory: 16Gi
        qosClass: Guaranteed
      networkInterfaceMultiqueue: Enable
      rootVolume:
        persistent:
          size: 80Gi
          storageClass: lvms-vg1
        type: Persistent
    type: KubeVirt
  release:
    image: quay.io/openshift-release-dev/ocp-release@sha256:27c93d3b308e9c3694dd7e448d71f61e4e3c033ad8905031736bd1912c1f41fc
  replicas: 2
